### ISSUE TITLE
"ZydisDecodedOperandMem_::ZydisDecodedOperandMemDisp_" has no member "has_displacement"

### ISSUE THREAD

**Issue by Smellon69** [notpidgey/EagleVM#10]
**Describe the bug**
"ZydisDecodedOperandMem_::ZydisDecodedOperandMemDisp_" has no member "has_displacement"

EagleVMCore, inst_handler_entry.cpp, line 217
there's one more instance of the same error, but I can't find it again.

![image](https://github.com/notpidgey/EagleVM/assets/74884194/282d7366-5288-4471-a9fe-92fd673dab17)

**Comment by notpidgey** [comment]
Can't seem to replicate this issue on my end for the Visual Studio 22 generator. 
Have you modified the project in any kind of way? Did you generate this solution using `cmake -G "Visual Studio 17"`?
Zydis should have been submoduled recursively and must not be missing the Zycore dependency.

There is not much info for me to work with or help you with.

**Comment by Smellon69** [comment]
> Can't seem to replicate this issue on my end for the Visual Studio 22 generator. Have you modified the project in any kind of way? Did you generate this solution using `cmake -G "Visual Studio 17"`? Zydis should have been submoduled recursively and must not be missing the Zycore dependency.
> 
> There is not much info for me to work with or help you with.

could you possible show a screenshot of where this is actually defined? I set everything up correctly, I think maybe I'm missing a file or something like that.

**Comment by notpidgey** [comment]
I mean sure I can but theres a bigger issue if this doesn't compile for you out of the box...
It should work just fine if you clone the project, recursively initialize submodules, and generate.

Have you tried cloning the project from scratch just now? Did you change anything like I asked before? You can always use git to reset any changes as well.

```cpp
/**
 * Extended info for memory-operands.
 */
typedef struct ZydisDecodedOperandMem_
{
    /**
     * The type of the memory operand.
     */
    ZydisMemoryOperandType type;
    /**
     * The segment register.
     */
    ZydisRegister segment;
    /**
     * The base register.
     */
    ZydisRegister base;
    /**
     * The index register.
     */
    ZydisRegister index;
    /**
     * The scale factor.
     */
    ZyanU8 scale;
    /**
     * Extended info for memory-operands with displacement.
     */
    struct ZydisDecodedOperandMemDisp_
    {
        /**
         * Signals, if the displacement value is used.
         */
        ZyanBool has_displacement;
        /**
         * The displacement value
         */
        ZyanI64 value;
    } disp;
} ZydisDecodedOperandMem;
```

**Comment by notpidgey** [comment]
Unconfirmed Zydis versioning issue / Won't fix.

**Comment by miltinhoc** [comment]
I get the same error, the `has_displacement ` does not seem to exist anymore

![image](https://github.com/user-attachments/assets/a11099a7-7628-4a13-a995-815de9d454bd)

I changed the part of the code with the error to `if (op_mem.disp.size != 0)` and it seemed to be fixed. I can build and it functions ok:
![image](https://github.com/user-attachments/assets/2990f76c-d083-4994-80ca-ab420ef52665)
