### ISSUE TITLE
Want to get involved

### ISSUE THREAD

**Issue by CodeApex** [notpidgey/EagleVM#4]
Hey Pidgey, I want to get involved in this project with you. Do you have a preferred method of contact so we can link up? I believe there is quite a bit I can offer to this to greatly benefit your project. I am also interested in talking with you about some future employment if you are up for it.

**Comment by notpidgey** [comment]
Hi! Thanks for reaching out about your interest in the project I really appreciate it. If you have Discord you can message me at "writecr3"
